---
deployment:
  tasks:
    - export WEBPATH=/home/danc/public_html/MPDashboard
    - /bin/mkdir -p $WEBPATH/admin_console
    - /bin/mkdir -p $WEBPATH/admin_console/assets
    - /bin/cp -f admin_console/*.php $WEBPATH/admin_console/ 2>/dev/null || true
    - /bin/cp -Rf admin_console/assets/* $WEBPATH/admin_console/assets/ 2>/dev/null || true
